### ISSUE TITLE
Please add sanction list to this list

### ISSUE THREAD

**Issue by mmrabbani** [filteryab/ir-blocked-domain#1]
Please add sanction list from "ir-sanctioned-domain" project to this project. So user can add a single .dat file and write different routing based on "ir-blocked-domain" or "ir-sanctioned-domain".

**Comment by filteryab** [comment]
> Please add sanction list from "ir-sanctioned-domain" project to this project. So user can add a single .dat file and write different routing based on "ir-blocked-domain" or "ir-sanctioned-domain".

Hi Mr Rabbani
Thank you for your suggestion
Merge done.
